module.exports={
    devServer:{
        open:true,//是否自动弹出浏览器页面
        host:'localhost',
        port:'8080',
        https:false,
        hotOnly:false,
        proxy:{
            '/love':{
                target:'http://127.0.0.1:8081',//API服务器地址
                changeOrigin:true,
                pathRewrite:{
                    '^/love':''
                }
            }
        }
    }
}